apiVersion: v1
kind: Pod
metadata:
  name: django-pod 
  labels:
    function: app
spec:
  containers:
  - name: django
    image: ghcr.io/cis91git2023/cis-92:Milestone-6.1
    ports:
    - containerPort: 8000